version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/node:lts
  steps:
    - checkout
    - restore_cache:
        key: - v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
             - v1-yarn-packages-
    - run:
        name: Install Dependencies
        command: yarn install
    - save_cache:
        name: Save Yarn Package Cache
        key: v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
            - ./node_modules/
    - run:
        name: Run Backend ESLint Check
        command: yarn lint \
            --format junit \
            --output-file ~/repo/reports/eslint/backend-lint-results.xml
    - run:
        name: Run Backend Tests
        command: yarn test
    - store_artifacts:
        path: ~/repo/reports
    - store_artifacts:
        path: ~/repo/backend/coverage
    - store_test_results:
        path: ~/repo/reports
